version: "3.8"

services:
  rabbitmq: 
    image: rabbitmq:3-management
    command: rabbitmq-server
    restart: unless-stopped
    ports:
      - 15672:15672
      - 5672:5672
  m1:
      restart: unless-stopped
      build:
        context: .
        dockerfile: ./m1/Dockerfile
      volumes:
        - ./m1:/app
      ports:
        - 3000:3000
      depends_on: 
        - rabbitmq
  m2:
      restart: unless-stopped
      build:
          context: .
          dockerfile: ./m2/Dockerfile
      volumes:
          - ./m2:/app
      depends_on: 
        - rabbitmq
  
